version: 2

before:
  hooks:
    - go mod download
builds:
  - main: .
    binary: gcsproxy
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - arm
      - 386
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - formats: ['tar.gz']
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        formats: ['zip']
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "SNAPSHOT-{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^test:'
      - 'README'
      - Merge pull request
      - Merge branch

# Push arch specific images (push is required for multi-arch manifests)
dockers:
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}-amd64"
    use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}-arm64"
    use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/arm64"

# Push multi-arch manifests
docker_manifests:
  # Github Container Registry
  - name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}-arm64"
  - name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{.Major}}.{{.Minor}}"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}-arm64"

release:
  footer: |
    ## Docker images
    [Packages gcsproxy](https://github.com/{{ .Env.GITHUB_REPOSITORY }}/pkgs/container/gcsproxy)
    ```shell
    docker pull ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}
    ```
